export const signupEmailTemplate = (code) => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">WELCOME</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Thanks for signing up.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">welcome to Backend Services . Please verify your email address to activate your account.</p><table role="presentation" style="margin-top:28px;"><tr><td bgcolor="#ffffff" style="border-radius:8px;">${code}</td></tr></table><p style="margin:28px 0 0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not create this account, you can safely ignore this email.</p></td></tr></table></td></tr></table></body></html>`;

export const passwordResetTokenEmailTemplate = (code) => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">PASSWORD RESET</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Reset your password.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">Use the code below to reset your password. It expires in 15 minutes.</p><div style="margin:28px 0;padding:18px;border:1px solid #52525b;border-radius:10px;background:#09090b;color:#fff;font-family:monospace;font-size:28px;font-weight:bold;letter-spacing:8px;text-align:center;">${code}</div><p style="margin:0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not request a password reset, please ignore this email.</p></td></tr></table></td></tr></table></body></html>`;

export const passwordResetNotificationEmailTemplate = () => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">SECURITY NOTICE</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Your password was changed.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">Hi John, this is a confirmation that the password for your account at Backend Services was changed successfully.</p><p style="margin:28px 0 0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not make this change, contact us immediately at superman@gmail.com.</p></td></tr></table></td></tr></table></body></html>`;

export const twoFactorEnabledEmailTemplate = () => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">SECURITY UPDATE</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Two-factor authentication is on.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">Hi John, two-factor authentication has been enabled for your account at Backend Services. You will now need a verification code when signing in.</p><p style="margin:28px 0 0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">Did not enable this? Contact us immediately at superman@gmail.com.</p></td></tr></table></td></tr></table></body></html>`;

export const twoFactorCodeEmailTemplate = (code) => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">SIGN-IN VERIFICATION</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Your verification code.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;"> Enter this code to finish signing in. It expires in 10 minutes.</p><div style="margin:28px 0;padding:18px;border:1px solid #52525b;border-radius:10px;background:#09090b;color:#fff;font-family:monospace;font-size:28px;font-weight:bold;letter-spacing:8px;text-align:center;">${code}</div><p style="margin:0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">Never share this code with anyone.</p></td></tr></table></td></tr></table></body></html>`;

export const emailVerificationTokenEmailTemplate = (code) => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">EMAIL VERIFICATION</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Verify your email address.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">Use this code to verify your email address. It expires in 1 hours.</p><div style="margin:28px 0;padding:18px;border:1px solid #52525b;border-radius:10px;background:#09090b;color:#fff;font-family:monospace;font-size:28px;font-weight:bold;letter-spacing:8px;text-align:center;">${code}</div><p style="margin:0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not request this verification, you can safely ignore this email.</p></td></tr></table></td></tr></table></body></html>`;

export const accountDeactivatedEmailTemplate = () => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">ACCOUNT UPDATE</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Your account has been deactivated.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">Your Backend Services account is now deactivated. You will not be able to sign in until it is reactivated.</p><p style="margin:28px 0 0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not request this change, contact us immediately at superman@gmail.com.</p></td></tr></table></td></tr></table></body></html>`;

export const accountReactivatedEmailTemplate = () => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">ACCOUNT UPDATE</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Your account has been reactivated.</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">Your Backend Services account is active again. You can now sign in and continue using Backend Services.</p><p style="margin:28px 0 0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not request this change, contact us immediately at superman@gmail.com.</p></td></tr></table></td></tr></table></body></html>`;

export const accountDeactivatedEmailcodeTemplate = (code) => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">ACCOUNT UPDATE</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Use this code to deactivate your account!</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">${code}</p><p style="margin:28px 0 0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not request this change, contact us immediately at superman@gmail.com.</p></td></tr></table></td></tr></table></body></html>`;
export const accountActivateEmailcodeTemplate = (code) => `
<!doctype html><html lang="en"><body style="margin:0;padding:32px 16px;background:#09090b;color:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#18181b;border:1px solid #3f3f46;border-radius:16px;"><tr><td style="padding:28px 36px;border-bottom:1px solid #3f3f46;font-size:20px;font-weight:700;color:#fff;">Backend Services</td></tr><tr><td style="padding:36px;"><p style="margin:0 0 12px;color:#a1a1aa;font-size:12px;font-weight:bold;letter-spacing:1.4px;">ACCOUNT UPDATE</p><h1 style="margin:0 0 16px;color:#fff;font-size:28px;">Use this code to Activate your account!</h1><p style="margin:0;color:#d4d4d8;font-size:16px;line-height:1.6;">${code}</p><p style="margin:28px 0 0;padding:14px 16px;background:#27272a;border-left:3px solid #71717a;color:#d4d4d8;font-size:14px;line-height:1.5;">If you did not request this change, contact us immediately at superman@gmail.com.</p></td></tr></table></td></tr></table></body></html>`;